### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by Bernardstanislas**
# Homepage

Thinking about what it could be, I will suggest multiple versions so we can discuss about them here.
## Movie catalog

image

### CODE REVIEW

**Comment by Bernardstanislas** [comment]
@Tommass @pierr ready to merge, just waiting for @Tommass to implement the Java side.
Functionnal on the mocked API

**Comment by Bernardstanislas** [comment]
@Tommass see [this implementation](https://github.com/KleeGroup/focus-demo-app/commit/414b3faaecc137f934faa928604d8330632c162a) as a starting point for the Java side

**Comment by pierr** [comment]
Many components could be pure functions, no?
The only problem is for `@TranslationBehaviour` which add a method inside the `this`
@Bernardstanislas

**Comment by pierr** [comment]
But it's great!

**Comment by pierr** [comment]
I let @Tommass merge it

**Comment by Bernardstanislas** [comment]
@pierr you were right, I fixed it, and used `focus-core/translation/translate`

**Comment by pierr** [comment]
lol

**Comment by pierr** [comment]
@Bernardstanislas Cool!

**Comment by pierr** [comment]
@Bernardstanislas  I was wondering about `translationBehaviour` if we could pass the function as `props` instead of using `this`

**Comment by pierr** [comment]
T

**Comment by pierr** [comment]
But this is more a FocusComponents related issue

**Comment by Bernardstanislas** [comment]
@pierr that could work but you would need to check whether the component provided to the behaviour is a function or a class, so that we keep the legacy compatibility by putting a `this.i18n` in classes and a `translate` prop in pure components

**Comment by pierr** [comment]
@Bernardstanislas Why wouldn't it works for both `class` and `function`, only `focus-components` uses this behaviour. Its just a rename `this.i18n` to `this.props.i18n` for `classes`

**Comment by Bernardstanislas** [comment]
@pierr yes but it would imply that all project might change their `this.i18n` to `this.props.i18n`

**Comment by pierr** [comment]
`ctrl+shift+r this.i18n` replace `this.props.i18n` 
toohard

**Pull request merged**
